name: Build AvalonCalendar
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build with Maven
        run: mvn -q -U -B clean package
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: AvalonCalendar
          path: target/avaloncalendar-*.jar
